import assert from 'node:assert/strict';import fs from 'node:fs';import {spawnSync} from 'node:child_process';
const avatars=JSON.parse(fs.readFileSync('public/avatars.json','utf8'));
assert(avatars.length>180,'Expected the Chimpions collection catalog');
assert(!avatars.some(a=>a.id==='steamboat-willie'||a.id==='chimpion'),'Special guest/default characters must not enter Ski');
assert.equal(new Set(avatars.map(a=>a.id)).size,avatars.length,'Avatar IDs must be unique');
assert(avatars.every(a=>a.name&&a.url),'Every Ski catalog entry must have a name and GLB URL');
console.log('PASS Chimpions Ski catalog:',avatars.length);
await import('./avatar-rig-compat-invariants.mjs');
const audit=spawnSync(process.execPath,['scripts/audit-avatar-rig-compat.mjs','--no-write'],{encoding:'utf8',env:{...process.env,RIG_AUDIT_EMIT_REPORT:'1'},maxBuffer:64*1024*1024});
process.stdout.write(audit.stdout||'');process.stderr.write(audit.stderr||'');
assert.equal(audit.status,0,'rig audit report emission failed');
