export const SKI_TUNING=Object.freeze({
  // Practical ski corridor: ±11.3 versus the previous ±8.1 (~39.5% wider).
  PLAYER_HALF_WIDTH:11.3,
  COURSE_OBJECT_HALF_WIDTH:10.2,
  SAFE_ROUTE_HALF_WIDTH:8.4,
  CONTENT_BAND_HALF_WIDTH:8.8,

  // Speed progression: ~60% faster opening pace, then modest 30-second tiers.
  BASE_SPEED:19.2,
  SPEED_TIER_SECONDS:30,
  SPEED_TIER_INCREMENT:1.9,
  MAX_SPEED:32.5,
  SPEED_RESPONSE:2.4,

  // Fast arcade carve response while retaining edge -> turn -> heading -> vx.
  INPUT_DEADZONE:.018,
  CONTROLLER_DEADZONE:.14,
  EDGE_RESPONSE:60,
  EDGE_RELEASE:26,
  EDGE_REVERSAL:90,
  CARVE_LOAD_RESPONSE:28,
  TURN_RATE_BASE:5.0,
  TURN_RATE_SPEED_BONUS:.35,
  TURN_INPUT_ASSIST:1.2,
  TURN_RESPONSE:40,
  TURN_REVERSAL_RESPONSE:64,
  COUNTER_HEADING_RESPONSE:28,
  HEADING_LIMIT_LOW:.60,
  HEADING_LIMIT_HIGH:.53,
  HEADING_RECENTER:9.0,
  TURN_RECENTER:16.0,
  LATERAL_SCALE_LOW:1.02,
  LATERAL_SCALE_HIGH:.74,
  LATERAL_RESPONSE:36,
  LATERAL_REVERSAL_RESPONSE:64,
  PLAYER_YAW_RESPONSE:14,
  PLAYER_BANK_RESPONSE:18,
  POSE_CARVE_BLEND:.28,
  POSE_REVERSAL_BLEND:.42,

  // Manual jump remains small; ramps produce the requested monster jump.
  MANUAL_JUMP_VELOCITY:5.9,
  RAMP_JUMP_BASE_VELOCITY:13.4,
  RAMP_JUMP_SPEED_FACTOR:.095,
  RAMP_RETRIGGER_GRACE:.85
});
